dist: bionic

language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

# Use a consistent Kafka version for each version of Ruby being tested.
env:
  - KAFKA=2.2

# Run tests against different versions of Kafka using whatever RVM considers
# the most recent stable version of Ruby to be.
jobs:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: ruby
      env: KAFKA=2.1
    - rvm: ruby
      pnv: KAFKA=2.2
    - rvm: ruby
      env: KAFKA=2.3
    - rvm: ruby
      env: KAFKA=2.4
    - rvm: ruby
      env: KAFKA=2.5

services:
  - docker

cache: bundler

before_install:
  - docker-compose -f spec/support/kafka-$KAFKA.yml up -d
  - gem install bundler -v 2.1.4

  # Install an up to date version of kafkacat via docker. The version available
  # in apt doesn't support nil keys or headers.
  - docker pull edenhill/kafkacat:1.5.0
  - echo 'docker run -i --rm --network=host edenhill/kafkacat:1.5.0 "$@"' > $HOME/bin/kafkacat
  - chmod +x $HOME/bin/kafkacat

  # Enable documentation format to better show what kafka error logs match with
  # which tests.
  - echo "--color --require './spec/support/running_documentation_formatter.rb' --format RunningDocumentationFormatter --warnings" > .rspec

script:
  - bundle exec rake
