version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: "wurstmeister/kafka:2.12-2.3.1"
    tmpfs:
      - /kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
