# frozen_string_literal: true

require_relative "../lib/kafka/version"

require "mini_portile2"
require "fileutils"

LIBRDKAFKA_VERSION  = "2.1.0"
LIBRDKAFKA_CHECKSUM = "d8e76c4b1cde99e283a19868feaaff5778aa5c6f35790036c5ef44bc5b5187aa"

desc "Compile librdkafka v#{LIBRDKAFKA_VERSION}"
task :default do
  Rake::Task["build:release"].invoke(LIBRDKAFKA_VERSION, LIBRDKAFKA_CHECKSUM)
end

desc "Clean up and remove build artifacts"
task :clean do
  FileUtils.rm_rf([
    File.join(__dir__, "tmp"),
    File.join(__dir__, "ports"),
    Dir.glob(File.join(__dir__, "librdkafka.*")),
  ])
end

namespace :build do
  # Build librdkafka and store the library into ext/
  #
  # NOTE: To speed up the build try:
  #   MAKE="make -j${nproc}" rake
  def build(version:, checksum: nil)
    recipe = MiniPortile.new("librdkafka", version)
    recipe.files << {
      url: "https://github.com/confluentinc/librdkafka/archive/#{version}.tar.gz",
      sha256: checksum,
    }
    recipe.configure_options = ["--host=#{recipe.host}"]
    recipe.cook

    ext = recipe.host.include?("darwin") ? "dylib" : "so"
    lib = File.join(recipe.path, "lib", "librdkafka.#{ext}")

    # cp will copy the content following any symlinks
    FileUtils.cp(lib, __dir__)

    # Remove build directories
    FileUtils.rm_rf([
      File.join(__dir__, "tmp"),
      File.join(__dir__, "ports"),
    ])
  end

  desc "Download and build an official release of librdkafka"
  task :release, [:version, :checksum] do |_task, args|
    version  = args[:version]
    checksum = args[:checksum]

    raise ArgumentError, "version is required" if version.nil?
    raise ArgumentError, "checksum is required" if checksum.nil?

    # Prefix the version string to look like "v1.3.0" so the URL is correct.
    version = version.start_with?("v") ? str : "v#{version}"

    build(version: version, checksum: checksum)
  end

  desc "Build librdkafka at the given git sha or tag"
  task :git, [:ref, :checksum] do |_task, args|
    build(version: args[:ref], checksum: args[:checksum])
  end
end
