name: Rubocop

on:
  - push
  - pull_request

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Current stable version of Ruby
        ruby-version: ruby
        bundler-cache: true

    - name: Rubocop
      run: bundle exec rubocop
